package org.arc.sys.hibernate.entities;
// Generated Jun 12, 2012 4:50:53 PM by Hibernate Tools 3.2.1.GA



/**
 * Branch generated by hbm2java
 */
public class Branch  implements java.io.Serializable {


     private Integer branchId;
     private String name;
     private String address;
     private Integer phone;
     private Boolean del;

    public Branch() {
    }

    public Branch(String name, String address, Integer phone, Boolean del) {
       this.name = name;
       this.address = address;
       this.phone = phone;
       this.del = del;
    }
   
    public Integer getBranchId() {
        return this.branchId;
    }
    
    public void setBranchId(Integer branchId) {
        this.branchId = branchId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Integer getPhone() {
        return this.phone;
    }
    
    public void setPhone(Integer phone) {
        this.phone = phone;
    }
    public Boolean getDel() {
        return this.del;
    }
    
    public void setDel(Boolean del) {
        this.del = del;
    }




}


