package org.arc.sys.hibernate.entities;
// Generated Jun 12, 2012 4:50:53 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * Buy generated by hbm2java
 */
public class Buy implements java.io.Serializable {

    private Integer buyid;
    private Integer userId;
    private Provider provider;
    private Date dateBuy;
    private double total;
    private boolean del;

    public Buy() {
    }

    public Buy(Date dateBuy, double totalBuy, boolean del) {
        this.dateBuy = dateBuy;
        this.total = totalBuy;
        this.del = del;
    }

    public Buy(Provider provider, Date dateBuy, double totalBuy, boolean del) {
        this.provider = provider;
        this.dateBuy = dateBuy;
        this.total = totalBuy;
        this.del = del;
    }

    public Integer getBuyid() {
        return this.buyid;
    }

    public void setBuyid(Integer buyid) {
        this.buyid = buyid;
    }

    public Date getDateBuy() {
        return this.dateBuy;
    }

    public void setDateBuy(Date dateBuy) {
        this.dateBuy = dateBuy;
    }

    public double getTotal() {
        return this.total;
    }

    public void setTotal(double totalBuy) {
        this.total = totalBuy;
    }

    public boolean isDel() {
        return this.del;
    }

    public void setDel(boolean del) {
        this.del = del;
    }

    public Provider getProvider() {
        return provider;
    }

    public void setProvider(Provider provider) {
        this.provider = provider;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    
}
