package org.arc.sys.hibernate.entities;
// Generated Jun 6, 2012 7:57:45 AM by Hibernate Tools 3.2.1.GA



/**
 * Credit generated by hbm2java
 */
public class Credit  implements java.io.Serializable {


     private Integer creditId;
     private Buy buy;
     private int userId;
     private double total;
     private boolean canceled;
     private boolean del;

    public Credit() {
    }

	
    public Credit(int total, boolean canceled, boolean del) {
        this.total = total;
        this.canceled = canceled;
        this.del = del;
    }
    public Credit(Buy buy, double total, boolean canceled, boolean del) {
       this.buy = buy;
       this.total = total;
       this.canceled = canceled;
       this.del = del;
    }
   
    public Integer getCreditId() {
        return this.creditId;
    }
    
    public void setCreditId(Integer creditId) {
        this.creditId = creditId;
    }
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }
    public boolean isCanceled() {
        return this.canceled;
    }
    
    public void setCanceled(boolean canceled) {
        this.canceled = canceled;
    }
    public boolean isDel() {
        return this.del;
    }
    
    public void setDel(boolean del) {
        this.del = del;
    }

    public Buy getBuy() {
        return buy;
    }

    public void setBuy(Buy buy) {
        this.buy = buy;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

}


