package org.arc.sys.hibernate.entities;
// Generated 15-07-2015 06:18:24 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CreditSale generated by hbm2java
 */
public class CreditSale  implements java.io.Serializable {


     private Long creditId;
     private double total;
     private boolean canceled;
     private boolean del;
     private Date createDate;
     
     private Set<PaymentSale> paymentSales;

    public CreditSale() {
    }

    public CreditSale(double total, boolean canceled, boolean del, Date createDate) {
       this.total = total;
       this.canceled = canceled;
       this.del = del;
       this.createDate = createDate;
    }
   
    public Long getCreditId() {
        return this.creditId;
    }
    
    public void setCreditId(Long creditId) {
        this.creditId = creditId;
    }
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }
    public boolean isCanceled() {
        return this.canceled;
    }
    
    public void setCanceled(boolean canceled) {
        this.canceled = canceled;
    }
    public boolean isDel() {
        return this.del;
    }
    
    public void setDel(boolean del) {
        this.del = del;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public Set<PaymentSale> getPaymentSales() {
        return paymentSales;
    }

    public void setPaymentSales(Set<PaymentSale> paymentSales) {
        this.paymentSales = paymentSales;
    }
}