package org.arc.sys.hibernate.entities;
// Generated Jun 12, 2012 4:50:53 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * Delivery generated by hbm2java
 */
public class Delivery implements java.io.Serializable {

    private Integer deliId;
    private Branch branch;
    private int userId;
    private Product product;
    private int amount;
    private Date dateDelivery;
    private boolean del;

    public Delivery() {
    }

    public Delivery(int amount, Date dateDelivery) {
        this.amount = amount;
        this.dateDelivery = dateDelivery;
    }

    public Delivery(Branch branch, Product product, int amount, Date dateDelivery, Boolean del) {
        this.branch = branch;
        this.product = product;
        this.amount = amount;
        this.dateDelivery = dateDelivery;
        this.del = del;
    }

    public Integer getDeliId() {
        return this.deliId;
    }

    public void setDeliId(Integer deliId) {
        this.deliId = deliId;
    }

    public int getAmount() {
        return this.amount;
    }

    public void setAmount(int amount) {
        this.amount = amount;
    }

    public Date getDateDelivery() {
        return this.dateDelivery;
    }

    public void setDateDelivery(Date dateDelivery) {
        this.dateDelivery = dateDelivery;
    }

    public boolean getDel() {
        return this.del;
    }

    public void setDel(boolean del) {
        this.del = del;
    }

    public Branch getBranch() {
        return branch;
    }

    public void setBranch(Branch branch) {
        this.branch = branch;
    }

    public Product getProduct() {
        return product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }
}
