package org.arc.sys.hibernate.entities;
// Generated Jun 12, 2012 4:41:57 PM by Hibernate Tools 3.2.1.GA



/**
 * Detailbuy generated by hbm2java
 */
public class Detailbuy  implements java.io.Serializable {


     private Integer detailBuyId;
     private Product product;
     private Buy buy;
     private int amount;
     private int consumed;
     private double priceBuy;
     private double totalBuy;
     private boolean exist;
     private boolean del;

    public Detailbuy() {
    }

    public Detailbuy(Product product, Buy buy, int amount, double priceBuy, double totalBuy, boolean del) {
       this.product = product;
       this.buy = buy;
       this.amount = amount;
       this.priceBuy = priceBuy;
       this.totalBuy = totalBuy;
       this.del = del;
    }
   
    public Integer getDetailBuyId() {
        return this.detailBuyId;
    }
    
    public void setDetailBuyId(Integer detailBuyId) {
        this.detailBuyId = detailBuyId;
    }

    public Buy getBuy() {
        return buy;
    }

    public void setBuy(Buy buy) {
        this.buy = buy;
    }

    public Product getProduct() {
        return product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    public int getAmount() {
        return amount;
    }

    public void setAmount(int amount) {
        this.amount = amount;
    }

    public boolean isDel() {
        return del;
    }

    public void setDel(boolean del) {
        this.del = del;
    }

    public double getPriceBuy() {
        return priceBuy;
    }

    public void setPriceBuy(double priceBuy) {
        this.priceBuy = priceBuy;
    }

    public boolean isExist() {
        return exist;
    }

    public void setExist(boolean exist) {
        this.exist = exist;
    }
    
    public double getTotalBuy() {
        return totalBuy;
    }

    public void setTotalBuy(double totalBuy) {
        this.totalBuy = totalBuy;
    }

    public int getConsumed() {
        return consumed;
    }

    public void setConsumed(int consumed) {
        this.consumed = consumed;
    }
    
}


