package org.arc.sys.hibernate.entities;
// Generated Jun 17, 2012 10:22:40 PM by Hibernate Tools 3.2.1.GA



/**
 * DetailRefund generated by hbm2java
 */
public class DetailRefund  implements java.io.Serializable {


     private Integer detailRefundId;
     private Branch branch;
     private Product product;
     private Refund refund;
     private int amount;
     private boolean del;

    public DetailRefund() {
    }

	
    public DetailRefund(int amount, boolean del) {
        this.amount = amount;
        this.del = del;
    }
    public DetailRefund(Branch branch, Product product, Refund refund, int amount, boolean del) {
       this.branch = branch;
       this.product = product;
       this.refund = refund;
       this.amount = amount;
       this.del = del;
    }

    public int getAmount() {
        return amount;
    }

    public void setAmount(int amount) {
        this.amount = amount;
    }

    public Branch getBranch() {
        return branch;
    }

    public void setBranch(Branch branch) {
        this.branch = branch;
    }

    public boolean isDel() {
        return del;
    }

    public void setDel(boolean del) {
        this.del = del;
    }

    public Integer getDetailRefundId() {
        return detailRefundId;
    }

    public void setDetailRefundId(Integer detailRefundId) {
        this.detailRefundId = detailRefundId;
    }

    public Product getProduct() {
        return product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    public Refund getRefund() {
        return refund;
    }

    public void setRefund(Refund refund) {
        this.refund = refund;
    }
   
    
}


