package org.arc.sys.hibernate.entities;
// Generated 22-04-2015 08:05:08 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * EmpProd generated by hbm2java
 */
public class EmpProd  implements java.io.Serializable {


     private Integer empProdId;
     private long productId;
     private long employeeId;
     private long commission;
     private Date createDate;

    public EmpProd() {
    }

    public EmpProd(long productId, long employeeId, long commission, Date createDate) {
       this.productId = productId;
       this.employeeId = employeeId;
       this.commission = commission;
       this.createDate = createDate;
    }
   
    public Integer getEmpProdId() {
        return this.empProdId;
    }
    
    public void setEmpProdId(Integer empProdId) {
        this.empProdId = empProdId;
    }
    public long getProductId() {
        return this.productId;
    }
    
    public void setProductId(long productId) {
        this.productId = productId;
    }
    public long getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(long employeeId) {
        this.employeeId = employeeId;
    }
    public long getCommission() {
        return this.commission;
    }
    
    public void setCommission(long commission) {
        this.commission = commission;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }




}


