package org.arc.sys.hibernate.entities;
// Generated Jun 12, 2012 4:50:53 PM by Hibernate Tools 3.2.1.GA



/**
 * Function generated by hbm2java
 */
public class Function  implements java.io.Serializable {


     private Integer functionId;
     private String nameFunc;
     private boolean del;

    public Function() {
    }

    public Function(String nameFunc, boolean del) {
       this.nameFunc = nameFunc;
       this.del = del;
    }
   
    public Integer getFunctionId() {
        return this.functionId;
    }
    
    public void setFunctionId(Integer functionId) {
        this.functionId = functionId;
    }
    public String getNameFunc() {
        return this.nameFunc;
    }
    
    public void setNameFunc(String nameFunc) {
        this.nameFunc = nameFunc;
    }
    public boolean isDel() {
        return this.del;
    }
    
    public void setDel(boolean del) {
        this.del = del;
    }




}


