package org.arc.sys.hibernate.entities;
// Generated Jun 6, 2012 7:57:45 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Payment generated by hbm2java
 */
public class Payment  implements java.io.Serializable {


     private Integer paymentId;
     private int userId;
     private Credit credit;
     private double amount;
     private Date datePayment;
     private Boolean del;

    public Payment() {
    }

	
    public Payment(double amount, Date datePayment) {
        this.amount = amount;
        this.datePayment = datePayment;
    }
    public Payment(Credit credit, double amount, Date datePayment, Boolean del) {
       this.credit = credit;
       this.amount = amount;
       this.datePayment = datePayment;
       this.del = del;
    }
   
    public Integer getPaymentId() {
        return this.paymentId;
    }
    
    public void setPaymentId(Integer paymentId) {
        this.paymentId = paymentId;
    }
    public double getAmount() {
        return this.amount;
    }
    
    public void setAmount(double amount) {
        this.amount = amount;
    }
    public Date getDatePayment() {
        return this.datePayment;
    }
    
    public void setDatePayment(Date datePayment) {
        this.datePayment = datePayment;
    }
    public Boolean getDel() {
        return this.del;
    }
    
    public void setDel(Boolean del) {
        this.del = del;
    }

    public Credit getCredit() {
        return credit;
    }

    public void setCredit(Credit credit) {
        this.credit = credit;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

}


