package org.arc.sys.hibernate.entities;
// Generated Jun 12, 2012 4:50:53 PM by Hibernate Tools 3.2.1.GA



/**
 * Person generated by hbm2java
 */
public class Person  implements java.io.Serializable {


     private Integer perId;
     private String names;
     private String firstname;
     private String lastname;
     private int ci;
     private String address;
     private Integer phoneAddress;
     private Integer phoneMobil;
     private String email;
     private Boolean del;

    public Person() {
    }

	
    public Person(String names, String firstname, String lastname, int ci, String address) {
        this.names = names;
        this.firstname = firstname;
        this.lastname = lastname;
        this.ci = ci;
        this.address = address;
    }
    public Person(String names, String firstname, String lastname, int ci, String address, Integer phoneAddress, Integer phoneMobil, String email, Boolean del) {
       this.names = names;
       this.firstname = firstname;
       this.lastname = lastname;
       this.ci = ci;
       this.address = address;
       this.phoneAddress = phoneAddress;
       this.phoneMobil = phoneMobil;
       this.email = email;
       this.del = del;
    }
   
    public Integer getPerId() {
        return this.perId;
    }
    
    public void setPerId(Integer perId) {
        this.perId = perId;
    }
    public String getNames() {
        return this.names;
    }
    
    public void setNames(String names) {
        this.names = names;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public int getCi() {
        return this.ci;
    }
    
    public void setCi(int ci) {
        this.ci = ci;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Integer getPhoneAddress() {
        return this.phoneAddress;
    }
    
    public void setPhoneAddress(Integer phoneAddress) {
        this.phoneAddress = phoneAddress;
    }
    public Integer getPhoneMobil() {
        return this.phoneMobil;
    }
    
    public void setPhoneMobil(Integer phoneMobil) {
        this.phoneMobil = phoneMobil;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Boolean getDel() {
        return this.del;
    }
    
    public void setDel(Boolean del) {
        this.del = del;
    }




}


