package org.arc.sys.hibernate.entities;
// Generated Jun 6, 2012 7:57:45 AM by Hibernate Tools 3.2.1.GA



/**
 * Provider generated by hbm2java
 */
public class Provider  implements java.io.Serializable {


     private Integer providerId;
     private String businessName;
     private Integer agent;
     private Boolean del;

    public Provider() {
    }

	
    public Provider(String businessName) {
        this.businessName = businessName;
    }
    public Provider(String businessName, Integer agent, Boolean del) {
       this.businessName = businessName;
       this.agent = agent;
       this.del = del;
    }
   
    public Integer getProviderId() {
        return this.providerId;
    }
    
    public void setProviderId(Integer providerId) {
        this.providerId = providerId;
    }
    public String getBusinessName() {
        return this.businessName;
    }
    
    public void setBusinessName(String businessName) {
        this.businessName = businessName;
    }
    public Integer getAgent() {
        return this.agent;
    }
    
    public void setAgent(Integer agent) {
        this.agent = agent;
    }
    public Boolean getDel() {
        return this.del;
    }
    
    public void setDel(Boolean del) {
        this.del = del;
    }




}


