package org.arc.sys.hibernate.entities;
// Generated Jun 12, 2012 4:50:53 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * RecordProducto generated by hbm2java
 */
public class RecordProducto  implements java.io.Serializable {


     private Integer rpId;
     private Product product;
     private String active;
     private Integer amount;
     private Date date;
     private double total;
     private Delivery delivery;
     private Buy buy;
     private DetailRefund detailRefund;
     private DetailSale sale;
     private boolean del;

    public RecordProducto() {
    }

    public RecordProducto(Product product, String active, Integer amount, Date date, double total, Delivery delivery, Buy buy, DetailRefund detailRefund, DetailSale sale, Boolean del) {
       this.product = product;
       this.active = active;
       this.amount = amount;
       this.date = date;
       this.total = total;
       this.delivery = delivery;
       this.buy = buy;
       this.detailRefund = detailRefund;
       this.sale = sale;
       this.del = del;
    }
   
    public Integer getRpId() {
        return this.rpId;
    }
    
    public void setRpId(Integer rpId) {
        this.rpId = rpId;
    }
    public String getActive() {
        return this.active;
    }
    
    public void setActive(String active) {
        this.active = active;
    }
    public Integer getAmount() {
        return this.amount;
    }
    
    public void setAmount(Integer amount) {
        this.amount = amount;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }
    public Delivery getDelivery() {
        return this.delivery;
    }
    
    public void setDelivery(Delivery delivery) {
        this.delivery = delivery;
    }
    public Buy getBuy() {
        return this.buy;
    }
    
    public void setBuy(Buy buy) {
        this.buy = buy;
    }
    public boolean getDel() {
        return this.del;
    }
    
    public void setDel(boolean del) {
        this.del = del;
    }

    public Product getProduct() {
        return product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    public DetailRefund getDetailRefund() {
        return detailRefund;
    }

    public void setDetailRefund(DetailRefund refund) {
        this.detailRefund = refund;
    }

    public DetailSale getSale() {
        return sale;
    }

    public void setSale(DetailSale sale) {
        this.sale = sale;
    }

}


