package org.arc.sys.hibernate.entities;
// Generated Jun 18, 2012 6:37:08 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Refund generated by hbm2java
 */
public class Refund  implements java.io.Serializable {


     private Integer refId;
     private Date dateRefund;
     private int userId;
     private int total;
     private boolean del;
     

    public Refund() {
    }

    public Refund(Date dateRefund, int total, boolean del) {
       this.dateRefund = dateRefund;
       this.total = total;
       this.del = del;
    }
   
    public Integer getRefId() {
        return this.refId;
    }
    
    public void setRefId(Integer refId) {
        this.refId = refId;
    }
    public Date getDateRefund() {
        return this.dateRefund;
    }
    
    public void setDateRefund(Date dateRefund) {
        this.dateRefund = dateRefund;
    }
    public int getTotal() {
        return this.total;
    }
    
    public void setTotal(int total) {
        this.total = total;
    }
    public boolean isDel() {
        return this.del;
    }
    
    public void setDel(boolean del) {
        this.del = del;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

}


