package org.arc.sys.hibernate.entities;
// Generated Jun 12, 2012 4:50:53 PM by Hibernate Tools 3.2.1.GA



/**
 * RolFun generated by hbm2java
 */
public class RolFun  implements java.io.Serializable {


     private RolFunId id;

    public RolFun() {
    }

    public RolFun(RolFunId id) {
       this.id = id;
    }
   
    public RolFunId getId() {
        return this.id;
    }
    
    public void setId(RolFunId id) {
        this.id = id;
    }




}


