package org.arc.sys.hibernate.entities;
// Generated Jun 12, 2012 4:50:53 PM by Hibernate Tools 3.2.1.GA



/**
 * UserRol generated by hbm2java
 */
public class UserRol  implements java.io.Serializable {


     private UserRolId id;

    public UserRol() {
    }

    public UserRol(UserRolId id) {
       this.id = id;
    }
   
    public UserRolId getId() {
        return this.id;
    }
    
    public void setId(UserRolId id) {
        this.id = id;
    }




}


