package org.arc.sys.hibernate.entities;
// Generated Jun 12, 2012 4:50:53 PM by Hibernate Tools 3.2.1.GA



/**
 * UserRolId generated by hbm2java
 */
public class UserRolId  implements java.io.Serializable {


     private int userId;
     private String rolId;

    public UserRolId() {
    }

    public UserRolId(int userId, String rolId) {
       this.userId = userId;
       this.rolId = rolId;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public String getRolId() {
        return this.rolId;
    }
    
    public void setRolId(String rolId) {
        this.rolId = rolId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserRolId) ) return false;
		 UserRolId castOther = ( UserRolId ) other; 
         
		 return (this.getUserId()==castOther.getUserId())
 && ( (this.getRolId()==castOther.getRolId()) || ( this.getRolId()!=null && castOther.getRolId()!=null && this.getRolId().equals(castOther.getRolId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserId();
         result = 37 * result + ( getRolId() == null ? 0 : this.getRolId().hashCode() );
         return result;
   }   


}


